services:
  dev-db:
    image: postgres:18.4
    ports:
      - "55432:5432"
    environment:
      - POSTGRES_USER=clojars
      - POSTGRES_PASSWORD=clojars
      - POSTGRES_DB=clojars
    volumes:
      - ./data/dev-postgres:/var/lib/postgresql
  test-db:
    image: postgres:18.4
    ports:
      - "55433:5432"
    environment:
      - POSTGRES_USER=clojars
      - POSTGRES_PASSWORD=clojars
      - POSTGRES_DB=clojars
    volumes:
      - ./data/test-postgres:/var/lib/postgresql
  s3mock:
    image: adobe/s3mock:5.2.2
    ports:
      - "9090:9090"
  elasticmq:
    image: "softwaremill/elasticmq:1.6.12"
    ports:
      - "9324:9324"
      - "9325:9325"
    volumes:
      - type: bind
        source: ./dev-resources/elasticmq.conf
        target: /opt/elasticmq.conf
        read_only: true

