version: 2.1
jobs:
  build:
    docker:
      - image: clojure:temurin-25-tools-deps-trixie
        environment:
          - DB_PORT: 5432
          - CLOJARS_ENVIRONMENT: test
      - image: postgres:12.1
        environment:
          - POSTGRES_USER=clojars
          - POSTGRES_PASSWORD=clojars
          - POSTGRES_DB=clojars
      - image: adobe/s3mock:5.2.2
    working_directory: ~/clojars
    steps:
      - checkout
      # Install some tooling we need that isn't on the image by default
      - run: apt update && apt install curl --yes && apt install unzip --yes
      - run:
          name: Download ElasticMQ
          command: curl https://s3-eu-west-1.amazonaws.com/softwaremill-public/elasticmq-server-1.6.12.jar -o elasticmq.jar
      - run:
          name: Run ElasticMQ
          command: java -Dconfig.file=dev-resources/elasticmq.conf -jar elasticmq.jar
          background: true
      - restore_cache:
          keys:
            - clojars-v1-{{ checksum "deps.edn" }}
            - clojars-v1-
      - run: make migrate-db
      - run: make check-dependabot
      - run: make lint
      - run: make test
      - save_cache:
          key: clojars-v1-{{ checksum "deps.edn" }}  
          paths:
            - ~/.m2/repository
      - store_test_results:
          path: target/test-results
