version: 2.1
jobs:
  build:
    docker:
      - image: clojure:temurin-25-tools-deps-bullseye
        environment:
          - DB_PORT: 5432
          - CLOJARS_ENVIRONMENT: test
      - image: postgres:12.1
        environment:
          - POSTGRES_USER=clojars
          - POSTGRES_PASSWORD=clojars
          - POSTGRES_DB=clojars
    working_directory: ~/clojars
    steps:
      - checkout
      - restore_cache:
          keys:
            - clojars-{{ checksum "deps.edn" }}
      - run: make prep-deps
      - save_cache:
          paths:
            - $HOME/.m2
          key: clojars-{{ checksum "deps.edn" }}
      # Install some tooling we need that isn't on the image by default
      - run: apt update && apt install curl --yes && apt install unzip --yes
      - run:
          name: Download MinIO
          command: |
            curl -fsSL --retry 3 https://github.com/minio/minio/releases/download/RELEASE.2023-04-20T17-56-55Z/minio.linux-amd64.RELEASE.2023-04-20T17-56-55Z -o minio
            echo "7eb3d4d8f570f5ff43dd0d3934be73459b901def1366509a0fed866d4b0ad6c7  minio" | sha256sum --check
            chmod +x minio
      - run:
          name: Run MinIO
          command: ./minio server /tmp/minio-data
          environment:
            MINIO_ROOT_USER: fake-access-key
            MINIO_ROOT_PASSWORD: fake-secret-key
          background: true
      - run:
          name: Wait for MinIO
          command: curl -fsS --retry 10 --retry-connrefused --retry-delay 1 --retry-max-time 30 http://localhost:9000/minio/health/ready
      - run:
          name: Download ElasticMQ
          command: curl https://s3-eu-west-1.amazonaws.com/softwaremill-public/elasticmq-server-1.6.12.jar -o elasticmq.jar
      - run:
          name: Run ElasticMQ
          command: java -Dconfig.file=dev-resources/elasticmq.conf -jar elasticmq.jar
          background: true
      - run: make migrate-db
      - run: make check-dependabot
      - run: make lint
      - run: make test
      - store_test_results:
          path: target/test-results
