version: 2.0
jobs:
  build:
    docker:
      - image: clojure:temurin-21-tools-deps-bullseye
        environment:
          - DB_PORT: 5432
          - CLOJARS_ENVIRONMENT: test
      - image: postgres:12.1
        environment:
          - POSTGRES_USER=clojars
          - POSTGRES_PASSWORD=clojars
          - POSTGRES_DB=clojars
      - image: minio/minio:RELEASE.2023-04-20T17-56-55Z
        command: server /data
        environment:
          MINIO_ROOT_USER: fake-access-key
          MINIO_ROOT_PASSWORD: fake-secret-key
    working_directory: ~/clojars
    steps:
      - checkout
      - restore_cache:
          keys:
            - clojars-{{ checksum "deps.edn" }}
      - run: make prep-deps
      - save_cache:
          paths:
            - $HOME/.m2
          key: clojars-{{ checksum "deps.edn" }}
      # Install some tooling we need that isn't on the image by default
      - run: apt update && apt install curl --yes && apt install unzip --yes
      - run:
          name: Download ElasticMQ
          command: curl https://s3-eu-west-1.amazonaws.com/softwaremill-public/elasticmq-server-1.4.2.jar -o elasticmq.jar
      - run:
          name: Run ElasticMQ
          command: java -Dconfig.file=dev-resources/elasticmq.conf -jar elasticmq.jar
          background: true
      - run: make migrate-db
      - run: make lint
      - run: make test
      - store_test_results:
          path: target/test-results
