#!/bin/bash
# Rebuilds the search index, then uploads it to s3
# Usage:
# rebuild-search-index releases/clojars-web-current.jar

set -e

dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

cd "$dir/.."

clojars_jar=$1

mkdir -p tmp

index_out=tmp/index-out.txt
java -cp "$clojars_jar" clojure.main -m clojars.tools.build-search-index production | tee "$index_out"

index_path=$(grep "index-path:" "$index_out" | sed -n 's/index-path: \(.*\)/\1/p')

index_archive=tmp/artifact-index.tgz

# upload the new index the s3 bucket
tar czf "$index_archive" "$index_path"

aws s3 cp --no-progress --content-type 'application/gzip' "$index_archive" "s3://clojars-artifact-index/"
