#!/bin/bash
# Rebuilds the search index, then uploads it to s3
# Usage:
# rebuild-search-index releases/clojars-web-current.jar

set -e

dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

cd "$dir/.."

clojars_jar=$1

java -cp "$clojars_jar" clojure.main -m clojars.tools.build-search-index production | tee /tmp/index-out.txt

index_path=$(grep "index-path:" /tmp/index-out.txt | sed -n 's/index-path: \(.*\)/\1/p')

# upload the new index the s3 bucket
tar czf /tmp/artifact-index.tgz "$index_path"

aws s3 cp --no-progress --content-type 'application/gzip' /tmp/artifact-index.tgz "s3://clojars-artifact-index/"
