#!/bin/bash
# Usage:
# maven-index-repo releases/clojars-web-current.jar indexer/indexer-core-4.1.2-cli.jar indexer/index-4.1.2 repo

set -e

clojars_jar=$1
indexer_jar=$2
# was the index_dir, see below
ignored=$3
repo=$4

CLOJARS_ENVIRONMENT=production
S3_REPO_BUCKET=clojars-repo-production

dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

source "$dir/set_default_java_opts.bash"

# Generate the pseudo-repo locally. We just need the pom files, and we export
# those from the db to avoid the cost of sync'ing the full bucket every run.
echo "Exporting poms..."
java "${JAVA_OPTS[@]}" -cp $clojars_jar clojure.main -m clojars.tools.export-poms $repo

# We only need the existing index files from s3
echo "Syncing index from s3..."
aws s3 sync "s3://$S3_REPO_BUCKET/.index/" "$repo/.index"

# generate the index shards
# 
# We use a temp dir for the index, as reusing the index results in an exception
# (see https://github.com/apache/maven-indexer/issues/720). This means that
# indexing is slightly slower (~45s longer), since it rebuilds the full index
# every time.
index_dir=$(mktemp --directory)
echo "Generating index..."
java "${JAVA_OPTS[@]}" -jar $indexer_jar \
    --name clojars \
    --type min \
    --index $index_dir \
    --destination $repo/.index \
    --repository $repo \
    --checksums \
    --quiet \
    --chunks \
    --keep 50

# remove old sums locally (the indexer removes old shards itself, but doesn't
# remove the sums for those shards)
echo "Removing stale checksum files..."
shopt -s extglob
pushd $repo/.index
for sum in @(*.gz.md5|*.gz.sha1); do
    shard=$(ls "$sum" | sed -e 's/\.md5//' -e 's/\.sha1//')
    if [ ! -f "$shard" ]; then
        rm "$sum"
    fi
done
popd

# upload new shards and sums to s3
echo "Uploading index shards to s3..."
java "${JAVA_OPTS[@]}" -cp $clojars_jar clojure.main -m clojars.tools.upload-repo-s3 $repo \
     $S3_REPO_BUCKET .index :gen-index 2> /dev/null

# remove old shards and sums from s3
echo "Deleting stale shards and checksums from s3..."
java "${JAVA_OPTS[@]}" -cp $clojars_jar clojure.main -m clojars.tools.remove-deletions-s3 $repo \
     $S3_REPO_BUCKET \
     .index 2> /dev/null

