#!/bin/bash
# Usage:
# update-stats releases/clojars-web-current.jar /var/log/nginx/clojars.access.log.1 data/stats 20161109

set -e

clojars_jar=$1
logfile=$2
output_dir=$3
DATE=$4

for_day=$output_dir/downloads-$DATE.edn
for_day_tmp=/tmp/downloads-$DATE.edn
combined=/tmp/downloads-$DATE-combined.edn
all=$output_dir/all.edn
all_tmp=/tmp/all.edn

cat $logfile | java -cp $clojars_jar clojure.main -m clojars.tools.process-stats > $for_day_tmp
java -cp $clojars_jar clojure.main -m clojars.tools.merge-stats $for_day $for_day_tmp > $combined
mv $combined $for_day
java -cp $clojars_jar clojure.main -m clojars.tools.merge-stats $all $for_day > $all_tmp
mv $all_tmp $all
