#!/bin/bash
# Usage:
# update-pom-list releases/clojars-web-current.jar

set -e

clojars_jar=$1

mkdir -p tmp

java -cp $clojars_jar clojure.main -m clojars.tools.generate-feeds tmp production 2> /dev/null
