#!/bin/bash
# Usage:
# update-stats releases/clojars-web-current.jar [20200120]

set -e

dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

clojars_jar=$1

date=$2
if [ -z "$date" ]; then
  date=$(date --date='1 day ago' +%Y%m%d)
fi

cdn_logfile=/tmp/cdn-access-yesterday.log

# generate the combined cdn stats first
"$dir"/combine-cdn-logs "$clojars_jar" "$cdn_logfile" "$date"

downloads_date=/tmp/downloads-$date.edn
downloads_all_old=/tmp/all-old.edn
downloads_all_new=/tmp/all-new.edn

# grab the latest all.edn from s3
aws s3 cp "s3://${S3_STATS_BUCKET}/all.edn" "$downloads_all_old"

cat "$cdn_logfile" | java -cp "$clojars_jar" clojure.main -m clojars.tools.process-stats > "$downloads_date"
java -cp "$clojars_jar" clojure.main -m clojars.tools.merge-stats "$downloads_all_old" "$downloads_date" > "$downloads_all_new"

# upload the new stats to the s3 bucket
aws s3 cp --acl public-read "$downloads_date" "s3://${S3_STATS_BUCKET}/"
aws s3 cp --acl public-read "$downloads_all_new" "s3://${S3_STATS_BUCKET}/all.edn"

# build index file
index="/tmp/index.html"
echo "<html><head><title>/</title></head><body><pre>" > $index
aws s3 ls "s3://${S3_STATS_BUCKET}/" | sed 's/\([a-z0-9-]*\.edn\)/<a href="\1">\1<\/a>/g' >> $index
echo >> $index
echo "</pre></body></html>" >> $index

# upload index to bucket
aws s3 cp --acl public-read "$index" "s3://${S3_STATS_BUCKET}/"
